apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip

spec:
  type: ClusterIP
  selectors:
    app: db
  ports:
    - port: 8080
      targetPort: 80
      
    - port: 9000
      targetPort: 3000